name: Sysdig IaC Scan

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'k8s-specifications/**'
      - '.github/workflows/sysdig-iac-scan.yaml'
  push:
    branches:
      - main
    paths:
      - 'k8s-specifications/**'
      - '.github/workflows/sysdig-iac-scan.yaml'

jobs:
  iac-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan Kubernetes IaC
        uses: sysdiglabs/scan-action@v6
        with:
          mode: iac
          iac-scan-path: ./k8s-specifications
          recursive: true
          cli-scanner-version: 1.9.0
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: https://app.us4.sysdig.com
          stop-on-failed-policy-eval: false
          stop-on-processing-error: true